[supabase]
url = "https://sxdpymomwdggmnbsbebe.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZHB5bW9td2RnZ21uYnNiZWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA5Mzg0NTEsImV4cCI6MjEwNjUxNDQ1MX0.x3rbEvfCY8BBITnjiC0i-IYVsI6_5DJUjtybPPFd1h0"
